name: Scrape and Push Stories

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:
    inputs:
      telegram:
        description: 'Is this triggered from Telegram? (yes or leave empty)'
        required: false
        default: ''
      url:
        description: 'URL (only for Telegram)'
        required: false
        default: ''
      pages:
        description: 'Page or Page Range (e.g., 1-3 or 5)'
        required: false
        default: ''

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 python-slugify

      - name: Run scraper with per-page commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "the5orcerer"
          git config user.email "rafansarukh@gmail.com"

          # Parse page range (default is 1-3)
          if [ "${{ github.event.inputs.pages }}" != "" ]; then
            PAGES="${{ github.event.inputs.pages }}"
          else
            PAGES="1-3"
          fi

          START_PAGE=$(echo "$PAGES" | cut -d '-' -f 1)
          END_PAGE=$(echo "$PAGES" | cut -d '-' -f 2)

          if [ "$END_PAGE" = "" ]; then
            END_PAGE=$START_PAGE
          fi

          for (( i=$START_PAGE; i<=$END_PAGE; i++ ))
          do
            echo "▶ Scraping page $i"

            if [ "${{ github.event.inputs.telegram }}" = "yes" ]; then
              python scrapper.py telegram "${{ github.event.inputs.url }}" "$i"
            else
              python scrapper.py "$i"
            fi

            git add src/stories/
            if git diff --cached --quiet; then
              echo "✅ No new content on page $i"
            else
              git commit -m "Auto-update: scraped page $i on $(date -u)"
              git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
              echo "✅ Committed and pushed page $i"
            fi

            sleep 5
          done
